# Refer to https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml for a working example
site_name: Ethereum Smart Contract Best Practices(日本語訳)
site_url: https://github.com/msykd/smart-contract-best-practices/
site_description: 
site_author: msykd
repo_url: https://github.com/msykd/smart-contract-best-practices/

pages:
  - ホーム: index.md
  - 基本的な知識: general_philosophy.md
  - 推奨する実装方法: recommendations.md
  - 既知の攻撃方法: known_attacks.md
  - リスクの備え方: software_engineering.md
  - Token specific recommendations: tokens.md
  - ドキュメント化の手法: documentation_procedures.md
  - 便利なツール: security_tools.md
  - セキュリティに関する情報: security_notifications.md
  - Smart Contract Security Bibliography: bibliography.md
  - List of Smart Contract Bug Bounty Programs: bug_bounty_list.md
  - About:
    - Reviewers: about/reviewers.md
    - License: about/license.md
    - Contributing: about/contributing.md

theme: 'material'
extra_css:
  - 'stylesheets/extra.css'
site_favicon: 'images/favicon.ico'



markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
